apiVersion: v1
kind: Service
metadata:
  name: billary-sales-service
spec:
  selector:
    app: billary-sales-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billary-sales-service
spec:
  selector:
    matchLabels:
      app: billary-sales-service
  replicas: 1
  template:
    metadata:
      labels:
        app: billary-sales-service
    spec:
      containers:
        - name: billary-sales-service
          image: localhost:32000/billary-sales-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "250Mi"
              cpu: "50m"
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: billary-websvc-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billary-websvc-secret
                  key: password