pipeline {
    agent {
        kubernetes {
          yamlFile 'k8s/KubernetesPod.yaml'
        }
    }
    stages {
        stage('Build') {
            steps {
                dir('billary-service-company') {
                    container('gradle') {
                        sh 'gradle clean build -x test'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                dir('billary-service-company') {
                    container('gradle') {
                        sh 'gradle -v'
                    }
                }
            }
        }
        stage('Build Image') {
            steps {
                dir('billary-service-company') {
                    container('docker') {
                         sh 'docker build -t localhost:32000/billary-company-service .'
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                dir('billary-service-company') {
                    container('docker') {
                         sh 'docker push localhost:32000/billary-company-service'
                    }
                }
            }
        }
        stage('Deployment') {
            steps {
                dir('billary-service-company') {
                    container('kubectl') {
                         sh 'kubectl delete -f k8s/Deployment.yaml -n default --ignore-not-found=true'
                         sh 'kubectl apply -f k8s/Deployment.yaml -n default'
                    }
                }
            }
        }
    }
}
